name: Docker image build

on:
  # push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jar_build:
    # Add write permission to packages so it can push to the Maven repository
    permissions:
      contents: read
      packages: write
    uses:
      CrawfordTech-Dev/reusable_workflows/.github/workflows/docker-upload.yml@main
    with:
      # java-version: '17'
      maven-params: '-DskipTests'
      # working-directory: './foo/'
    secrets:
      token: ${{ secrets.PACKAGE_REPO_TOKEN }} # pass token to access other private dependencies
      # token: ${{ secrets.GITHUB_TOKEN }} # otherwise pass the default token
