name: Java maven release

on:
  # push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jar_release:
    runs-on: ubuntu-latest
    # Add write permission to packages so it can update the pom version and push to the Maven repository
    permissions:
      contents: write
      packages: write

    steps:
    # - run: echo '${{ toJSON(github) }}'

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0
          distribution: 'temurin'
          cache: maven
          # server-id: github # value of repository/id field of the pom.xml
          # server-username: GITHUB_USER_REF  # env variable name for username
          # server-password: GITHUB_TOKEN_REF # env variable name for GitHub Personal Access Token
 
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Build with Maven
        run: mvn -B release:prepare release:perform --file pom.xml
        env:
          # GITHUB_TOKEN_REF: ${{ secrets.PACKAGE_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
