name: Java build

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jar_build:
    uses:
      mburton-crawfordtech/test_workflows/workflows/java-maven-build.yml@main
    # with:
      # java-version: 11.0
      # maven-params: '-DskipTests'
      # working-directory: './foo/'
    secrets:
      token: ${{ secrets.PACKAGE_REPO_TOKEN }} # pass token to access other private dependencies
      # token: ${{ secrets.GITHUB_TOKEN }} # otherwise pass the default token
