# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven Deploy

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jar_build:
    uses:
      mburton-crawfordtech/test_workflows/.github/workflows/java-maven-deploy.yml@main
