name: Java maven release

on:
  # push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jar_release:
    # Add write permission to packages so it can update the pom version and push to the Maven repository
    permissions:
      contents: write
      packages: write

    uses:
      CrawfordTech-Dev/reusable_workflows/.github/workflows/java-maven-release.yml@main
    # with:
      # java-version: '17'
      #maven-params: '-DskipTests'
      # working-directory: './foo/'
      # token: '${{ secrets.PACKAGE_REPO_TOKEN }}'
    secrets:
      token: ${{ secrets.PACKAGE_REPO_TOKEN }} # pass token to access other private dependencies
      # token: ${{ secrets.GITHUB_TOKEN }} # otherwise pass the default token
